/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    leads: Lead;
    projects: Project;
    sites: Site;
    categories: Category;
    media: Media;
    articles: Article;
    'page-home': PageHome;
    'page-features': PageFeature;
    'page-solutions': PageSolution;
    'page-pricing': PagePricing;
    forms: Form;
    users: User;
    memberships: Membership;
    'lead-activities': LeadActivity;
    'reminder-rules': ReminderRule;
    'reminder-notices': ReminderNotice;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'page-home': PageHomeSelect<false> | PageHomeSelect<true>;
    'page-features': PageFeaturesSelect<false> | PageFeaturesSelect<true>;
    'page-solutions': PageSolutionsSelect<false> | PageSolutionsSelect<true>;
    'page-pricing': PagePricingSelect<false> | PagePricingSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    'lead-activities': LeadActivitiesSelect<false> | LeadActivitiesSelect<true>;
    'reminder-rules': ReminderRulesSelect<false> | ReminderRulesSelect<true>;
    'reminder-notices': ReminderNoticesSelect<false> | ReminderNoticesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * Customer leads from public forms and manual entry, tracked step by step.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  title?: string | null;
  /**
   * The project this lead belongs to.
   */
  project: number | Project;
  /**
   * Contact name.
   */
  name?: string | null;
  /**
   * Phone number (share with wechat at least one).
   */
  phone?: string | null;
  /**
   * WeChat ID (share with phone at least one).
   */
  wechat?: string | null;
  /**
   * Company or store name (optional).
   */
  company?: string | null;
  /**
   * Customer-stated need or current situation.
   */
  note?: string | null;
  /**
   * Lead source channel (for tagging).
   */
  source?: ('website' | 'campaign' | 'douyin' | 'xiaohongshu' | 'manual' | 'support' | 'referral') | null;
  /**
   * Current owner.
   */
  owner?: (number | null) | User;
  /**
   * Current follow-up stage.
   */
  status?: ('new' | 'contacted' | 'converted' | 'closed') | null;
  /**
   * Deal amount recorded when converted (CNY, optional).
   */
  dealAmount?: number | null;
  /**
   * Dedupe key (phone or wechat), auto-written.
   */
  dedupKey?: string | null;
  /**
   * Most recent follow-up note.
   */
  followUpNote?: string | null;
  /**
   * Reminder for the next follow-up.
   */
  nextFollowUpAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Each product or focus area is a project; leads are grouped by project.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  /**
   * Unique URL-friendly English identifier.
   */
  slug: string;
  /**
   * One sentence on what this project does.
   */
  description?: string | null;
  /**
   * Current operating status.
   */
  status?: ('active' | 'beta' | 'archived') | null;
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * Public homepage URL (optional).
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown as the lead owner, etc.
   */
  name?: string | null;
  /**
   * Determines accessible collections.
   */
  role?: ('operator' | 'editor' | 'admin') | null;
  /**
   * Profile image (optional).
   */
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  /**
   * For system notifications (optional).
   */
  email?: string | null;
  /**
   * Unique login username for the admin.
   */
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manage covers, site logos, avatars and other image assets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessibility alternative text; recommended for main images.
   */
  alt?: string | null;
  /**
   * Optional caption below the image.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * A project can have multiple independent sites, each with its own SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  /**
   * The project this site belongs to.
   */
  project: number | Project;
  /**
   * Subdomain (e.g. demo), blank to use the project default.
   */
  subdomain?: string | null;
  /**
   * Path identifier (e.g. /home) to distinguish site pages.
   */
  pathSlug?: string | null;
  /**
   * Mark as a reusable template for cloning new sites.
   */
  isTemplate?: boolean | null;
  /**
   * Site publishing status.
   */
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * Site logo (400×100 transparent PNG recommended).
   */
  logo?: (number | null) | Media;
  /**
   * Accent color in hex, e.g. #2f8f96.
   */
  themeColor?: string | null;
  /**
   * Browser title, keep under 60 chars.
   */
  metaTitle?: string | null;
  /**
   * Search snippet, keep under 120 chars.
   */
  metaDescription?: string | null;
  /**
   * Social share preview image (1200×630).
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL identifier; blank will be derived from the name.
   */
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product ideas, solutions and growth practices with rich text and images.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Cover image for cards and share previews.
   */
  coverImage?: (number | null) | Media;
  title: string;
  /**
   * Unique URL identifier; blank will be derived from the title.
   */
  slug: string;
  /**
   * The project this article belongs to.
   */
  project: number | Project;
  /**
   * One-line summary for list cards and excerpts.
   */
  excerpt?: string | null;
  /**
   * Article category (optional).
   */
  category?: (number | null) | Category;
  /**
   * Topic tags for grouping and search.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Byline; blank defaults to the organization name.
   */
  author?: string | null;
  /**
   * Estimated reading time; blank auto-estimates.
   */
  readingMinutes?: number | null;
  /**
   * Body content with headings, lists, quotes, code, images, etc.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Page title (≤60 chars); blank uses the article title.
   */
  seoTitle?: string | null;
  /**
   * Page summary (≤120 chars); blank uses the excerpt.
   */
  seoDescription?: string | null;
  /**
   * Drafts are admin-only; publish to go live.
   */
  status: 'draft' | 'published';
  /**
   * Publish time; auto-filled on publish if blank.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Home page copy per project; rebuild the static site after editing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home".
 */
export interface PageHome {
  id: number;
  /**
   * The project this page copy belongs to; one record per project per page collection.
   */
  project: number | Project;
  /**
   * Drafts stay in admin; the static build reads published only.
   */
  status: 'draft' | 'published';
  meta: {
    title: string;
    description: string;
  };
  hero: {
    kicker: string;
    /**
     * One entry per title line; reorder freely. Emphasis renders the line highlighted.
     */
    titleLines: {
      text: string;
      emphasis?: boolean | null;
      id?: string | null;
    }[];
    desc: string;
    primary: {
      label: string;
      action: 'lead' | 'href';
      /**
       * Used when action is a link: /path/ internal, //host/ external.
       */
      href?: string | null;
    };
    secondary: {
      label: string;
      href: string;
    };
    /**
     * Hero bullet points, rendered in list order.
     */
    stats: {
      strong: string;
      span: string;
      id?: string | null;
    }[];
    diagram: {
      coreName: string;
      coreSub: string;
      /**
       * Max 3: the renderer stacks y offsets (92 + i*112) inside a fixed viewBox; more overflow.
       */
      nodes: {
        no: string;
        name: string;
        sub: string;
        tone: 'saas' | 'erp' | 'yunque';
        id?: string | null;
      }[];
      /**
       * Exactly 3: the renderer maps items 1/2/3 to chip-a/b/c slots; extras are dropped, gaps left blank.
       */
      chips: string[];
    };
  };
  products: {
    kicker: string;
    heading: string;
    desc: string;
    spotlight: {
      tag: string;
      icon: 'saas' | 'erp' | 'yunque';
      name: string;
      desc: string;
      points: string[];
      link: {
        label: string;
        href: string;
        external?: boolean | null;
      };
    };
    side: {
      tag: string;
      icon: 'saas' | 'erp' | 'yunque';
      name: string;
      desc: string;
      link: {
        label: string;
        href: string;
        external?: boolean | null;
      };
      id?: string | null;
    }[];
  };
  solutions: {
    kicker: string;
    /**
     * Newlines allowed: rendered as <br>; stored verbatim.
     */
    heading: string;
    moreLabel: string;
    moreHref: string;
    rows: {
      title: string;
      audience: string;
      desc: string;
      points: string[];
      id?: string | null;
    }[];
  };
  cases: {
    kicker: string;
    /**
     * Newlines allowed: rendered as <br>; stored verbatim.
     */
    heading: string;
    feature: {
      band: string;
      title: string;
      desc: string;
      metrics: {
        value: string;
        label: string;
        id?: string | null;
      }[];
    };
    /**
     * Max 2: labels come from an A/B pair by index, so a third entry renders undefined.
     */
    minis: {
      band: string;
      /**
       * Blank keeps the default styling (only some cards set a tone).
       */
      tone?: ('saas' | 'erp' | 'yunque') | null;
      title: string;
      desc: string;
      tag: string;
      id?: string | null;
    }[];
  };
  resource: {
    kicker: string;
    heading: string;
    desc: string;
    links: {
      title: string;
      sub: string;
      href: string;
      external?: boolean | null;
      id?: string | null;
    }[];
  };
  cta: {
    kicker: string;
    heading: string;
    desc: string;
    /**
     * Rendered in list order; reorder freely in admin.
     */
    rows: {
      icon: 'saas' | 'erp' | 'yunque';
      head: string;
      desc: string;
      act: string;
      action: 'lead' | 'href';
      href?: string | null;
      external?: boolean | null;
      id?: string | null;
    }[];
  };
  blog: {
    kicker: string;
    heading: string;
    desc: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Features page copy per project; rebuild the static site after editing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-features".
 */
export interface PageFeature {
  id: number;
  /**
   * The project this page copy belongs to; one record per project per page collection.
   */
  project: number | Project;
  /**
   * Drafts stay in admin; the static build reads published only.
   */
  status: 'draft' | 'published';
  meta: {
    title: string;
    description: string;
  };
  hero: {
    kicker: string;
    /**
     * One entry per title line; emphasis renders that line highlighted (the old two-field split lives here now).
     */
    titleLines: {
      text: string;
      emphasis?: boolean | null;
      id?: string | null;
    }[];
    description: string;
    stats: {
      value: string;
      label: string;
      id?: string | null;
    }[];
  };
  /**
   * Entries and panel kinds differ per site; rows are reorderable.
   */
  caps: {
    no: string;
    tag: string;
    /**
     * Blank keeps the default tag style; yb is the warm-gold variant.
     */
    tagTone?: 'yb' | null;
    title: string;
    /**
     * Swap the text and panel sides for visual rhythm.
     */
    reverse?: boolean | null;
    aside: {
      p: string;
      points: string[];
    };
    /**
     * Exactly one panel per capability (blockType carries the original kind discriminator).
     */
    panel: (
      | {
          badge: string;
          title: string;
          blocks: {
            no: string;
            name: string;
            note: string;
            /**
             * A CSS width like 72%; a layout geometry value, not a quantity.
             */
            w: string;
            id?: string | null;
          }[];
          id?: string | null;
          blockName?: string | null;
          blockType: 'blocks';
        }
      | {
          badge: string;
          title: string;
          chips: string[];
          rows: {
            label: string;
            /**
             * Numeric bar width (treated as 0-100 by the renderer), unlike the percent text in blocks.
             */
            w: number;
            val: string;
            id?: string | null;
          }[];
          id?: string | null;
          blockName?: string | null;
          blockType: 'chips';
        }
      | {
          badge: string;
          title: string;
          kpis: {
            val: string;
            label: string;
            id?: string | null;
          }[];
          bars: number[];
          months: string[];
          id?: string | null;
          blockName?: string | null;
          blockType: 'bars';
        }
      | {
          badge: string;
          title: string;
          steps: string[];
          id?: string | null;
          blockName?: string | null;
          blockType: 'journey';
        }
      | {
          badge: string;
          title: string;
          core: string;
          pegs: {
            /**
             * Anchor slot: the renderer places p1-p4 at fixed coordinates.
             */
            pos: 'p1' | 'p2' | 'p3' | 'p4';
            icon: 'task' | 'memory' | 'gov' | 'ext';
            text: string;
            id?: string | null;
          }[];
          id?: string | null;
          blockName?: string | null;
          blockType: 'agent';
        }
    )[];
    id?: string | null;
  }[];
  base: {
    kicker: string;
    heading: string;
    items: {
      title: string;
      desc: string;
      id?: string | null;
    }[];
  };
  cta: {
    kicker: string;
    heading: string;
    desc: string;
    btnText: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Solutions page copy per project (accordion by industry); rebuild the static site after editing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-solutions".
 */
export interface PageSolution {
  id: number;
  /**
   * The project this page copy belongs to; one record per project per page collection.
   */
  project: number | Project;
  /**
   * Drafts stay in admin; the static build reads published only.
   */
  status: 'draft' | 'published';
  meta: {
    title: string;
    description: string;
  };
  hero: {
    kicker: string;
    /**
     * One entry per title line; emphasis renders that line highlighted (the old two-field split lives here now).
     */
    titleLines: {
      text: string;
      emphasis?: boolean | null;
      id?: string | null;
    }[];
    description: string;
    stats: {
      value: string;
      label: string;
      id?: string | null;
    }[];
  };
  /**
   * One entry per accordion industry; list order is the display order.
   */
  industries: {
    label: string;
    /**
     * Product name shown beside the industry, e.g. Juece SaaS.
     */
    meta: string;
    blurb: string;
    tone: 'saas' | 'erp' | 'yunque';
    painPoints: string[];
    solutions: string[];
    scenarios: {
      title: string;
      desc: string;
      id?: string | null;
    }[];
    id?: string | null;
  }[];
  cta: {
    kicker: string;
    heading: string;
    desc: string;
    btnText: string;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Pricing page copy per project (plans, cross-product links, FAQ); rebuild the static site after editing.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-pricing".
 */
export interface PagePricing {
  id: number;
  /**
   * The project this page copy belongs to; one record per project per page collection.
   */
  project: number | Project;
  /**
   * Drafts stay in admin; the static build reads published only.
   */
  status: 'draft' | 'published';
  meta: {
    title: string;
    description: string;
  };
  hero: {
    kicker: string;
    /**
     * One entry per title line; emphasis renders that line highlighted (the old two-field split lives here now).
     */
    titleLines: {
      text: string;
      emphasis?: boolean | null;
      id?: string | null;
    }[];
    description: string;
  };
  /**
   * Three plans per site with independent billing models; rows are reorderable.
   */
  plans: {
    name: string;
    price: string;
    /**
     * Billing unit such as /year; blank for per-project or quote-based plans.
     */
    unit?: string | null;
    /**
     * Currency glyph; blank falls through to the renderer default of ¥. Leave blank for quotes.
     */
    currency?: string | null;
    desc: string;
    btnText: string;
    /**
     * Renders this card emphasized, with an optional badge.
     */
    highlight?: boolean | null;
    /**
     * Badge on the highlighted card, e.g. 重点推荐; blank uses the renderer default.
     */
    recTag?: string | null;
    features: string[];
    id?: string | null;
  }[];
  eco: {
    kicker: string;
    heading: string;
    desc: string;
    links: {
      label: string;
      href: string;
      /**
       * Outlined secondary button styling.
       */
      ghost?: boolean | null;
      id?: string | null;
    }[];
  };
  /**
   * Rendered in list order; rows are reorderable.
   */
  faqs: {
    q: string;
    a: string;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Define lead-capture form fields and submission target on public pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  name: string;
  /**
   * Owning site (optional, reusable globally).
   */
  site?: (number | null) | Site;
  /**
   * Only active forms are used on public pages.
   */
  status?: ('draft' | 'active') | null;
  /**
   * Field structure (JSON): names, required flags, order, etc.
   */
  fields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Multi-project governance: assign admin users to projects with scoped roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  title?: string | null;
  /**
   * The project this member belongs to.
   */
  project: number | Project;
  /**
   * The admin user account.
   */
  user: number | User;
  /**
   * owner/admin manage members; editor/owner/admin write; viewer read-only.
   */
  role: 'owner' | 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
}
/**
 * System-recorded key events for each lead. Read-only timeline of the lead lifecycle.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-activities".
 */
export interface LeadActivity {
  id: number;
  lead: number | Lead;
  project: number | Project;
  type: 'created' | 'status_changed' | 'assigned' | 'follow_up' | 'reminder';
  /**
   * Human-readable description of this event.
   */
  detail?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Who triggered this event (auto-written).
   */
  actor?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure follow-up reminder rules (due / first-response SLA), consumed by the scheduled scan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminder-rules".
 */
export interface ReminderRule {
  id: number;
  name: string;
  /**
   * Empty means a global rule for all projects.
   */
  project?: (number | null) | Project;
  kind: 'due' | 'sla';
  applyStatuses: ('new' | 'contacted' | 'converted' | 'closed')[];
  /**
   * Only for SLA: exceeds this many hours since creation without first response.
   */
  graceHours?: number | null;
  /**
   * Empty means remind the lead owner.
   */
  target?: (number | null) | User;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Follow-up records triggered by reminder rules; mark as done when handled.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminder-notices".
 */
export interface ReminderNotice {
  id: number;
  lead: number | Lead;
  project: number | Project;
  rule: number | ReminderRule;
  kind: 'due' | 'sla';
  /**
   * Rule target or the lead owner.
   */
  receiver?: (number | null) | User;
  status: 'open' | 'done';
  /**
   * When the reminder was due.
   */
  dueAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'page-home';
        value: number | PageHome;
      } | null)
    | ({
        relationTo: 'page-features';
        value: number | PageFeature;
      } | null)
    | ({
        relationTo: 'page-solutions';
        value: number | PageSolution;
      } | null)
    | ({
        relationTo: 'page-pricing';
        value: number | PagePricing;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'lead-activities';
        value: number | LeadActivity;
      } | null)
    | ({
        relationTo: 'reminder-rules';
        value: number | ReminderRule;
      } | null)
    | ({
        relationTo: 'reminder-notices';
        value: number | ReminderNotice;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  name?: T;
  phone?: T;
  wechat?: T;
  company?: T;
  note?: T;
  source?: T;
  owner?: T;
  status?: T;
  dealAmount?: T;
  dedupKey?: T;
  followUpNote?: T;
  nextFollowUpAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  status?: T;
  contactName?: T;
  contactEmail?: T;
  contactPhone?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  project?: T;
  subdomain?: T;
  pathSlug?: T;
  isTemplate?: T;
  status?: T;
  logo?: T;
  themeColor?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  coverImage?: T;
  title?: T;
  slug?: T;
  project?: T;
  excerpt?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  readingMinutes?: T;
  body?: T;
  seoTitle?: T;
  seoDescription?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home_select".
 */
export interface PageHomeSelect<T extends boolean = true> {
  project?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        kicker?: T;
        titleLines?:
          | T
          | {
              text?: T;
              emphasis?: T;
              id?: T;
            };
        desc?: T;
        primary?:
          | T
          | {
              label?: T;
              action?: T;
              href?: T;
            };
        secondary?:
          | T
          | {
              label?: T;
              href?: T;
            };
        stats?:
          | T
          | {
              strong?: T;
              span?: T;
              id?: T;
            };
        diagram?:
          | T
          | {
              coreName?: T;
              coreSub?: T;
              nodes?:
                | T
                | {
                    no?: T;
                    name?: T;
                    sub?: T;
                    tone?: T;
                    id?: T;
                  };
              chips?: T;
            };
      };
  products?:
    | T
    | {
        kicker?: T;
        heading?: T;
        desc?: T;
        spotlight?:
          | T
          | {
              tag?: T;
              icon?: T;
              name?: T;
              desc?: T;
              points?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                  };
            };
        side?:
          | T
          | {
              tag?: T;
              icon?: T;
              name?: T;
              desc?: T;
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    external?: T;
                  };
              id?: T;
            };
      };
  solutions?:
    | T
    | {
        kicker?: T;
        heading?: T;
        moreLabel?: T;
        moreHref?: T;
        rows?:
          | T
          | {
              title?: T;
              audience?: T;
              desc?: T;
              points?: T;
              id?: T;
            };
      };
  cases?:
    | T
    | {
        kicker?: T;
        heading?: T;
        feature?:
          | T
          | {
              band?: T;
              title?: T;
              desc?: T;
              metrics?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
            };
        minis?:
          | T
          | {
              band?: T;
              tone?: T;
              title?: T;
              desc?: T;
              tag?: T;
              id?: T;
            };
      };
  resource?:
    | T
    | {
        kicker?: T;
        heading?: T;
        desc?: T;
        links?:
          | T
          | {
              title?: T;
              sub?: T;
              href?: T;
              external?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        kicker?: T;
        heading?: T;
        desc?: T;
        rows?:
          | T
          | {
              icon?: T;
              head?: T;
              desc?: T;
              act?: T;
              action?: T;
              href?: T;
              external?: T;
              id?: T;
            };
      };
  blog?:
    | T
    | {
        kicker?: T;
        heading?: T;
        desc?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-features_select".
 */
export interface PageFeaturesSelect<T extends boolean = true> {
  project?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        kicker?: T;
        titleLines?:
          | T
          | {
              text?: T;
              emphasis?: T;
              id?: T;
            };
        description?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  caps?:
    | T
    | {
        no?: T;
        tag?: T;
        tagTone?: T;
        title?: T;
        reverse?: T;
        aside?:
          | T
          | {
              p?: T;
              points?: T;
            };
        panel?:
          | T
          | {
              blocks?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    blocks?:
                      | T
                      | {
                          no?: T;
                          name?: T;
                          note?: T;
                          w?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              chips?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    chips?: T;
                    rows?:
                      | T
                      | {
                          label?: T;
                          w?: T;
                          val?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              bars?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    kpis?:
                      | T
                      | {
                          val?: T;
                          label?: T;
                          id?: T;
                        };
                    bars?: T;
                    months?: T;
                    id?: T;
                    blockName?: T;
                  };
              journey?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    steps?: T;
                    id?: T;
                    blockName?: T;
                  };
              agent?:
                | T
                | {
                    badge?: T;
                    title?: T;
                    core?: T;
                    pegs?:
                      | T
                      | {
                          pos?: T;
                          icon?: T;
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  base?:
    | T
    | {
        kicker?: T;
        heading?: T;
        items?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        kicker?: T;
        heading?: T;
        desc?: T;
        btnText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-solutions_select".
 */
export interface PageSolutionsSelect<T extends boolean = true> {
  project?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        kicker?: T;
        titleLines?:
          | T
          | {
              text?: T;
              emphasis?: T;
              id?: T;
            };
        description?: T;
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  industries?:
    | T
    | {
        label?: T;
        meta?: T;
        blurb?: T;
        tone?: T;
        painPoints?: T;
        solutions?: T;
        scenarios?:
          | T
          | {
              title?: T;
              desc?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        kicker?: T;
        heading?: T;
        desc?: T;
        btnText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-pricing_select".
 */
export interface PagePricingSelect<T extends boolean = true> {
  project?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        kicker?: T;
        titleLines?:
          | T
          | {
              text?: T;
              emphasis?: T;
              id?: T;
            };
        description?: T;
      };
  plans?:
    | T
    | {
        name?: T;
        price?: T;
        unit?: T;
        currency?: T;
        desc?: T;
        btnText?: T;
        highlight?: T;
        recTag?: T;
        features?: T;
        id?: T;
      };
  eco?:
    | T
    | {
        kicker?: T;
        heading?: T;
        desc?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              ghost?: T;
              id?: T;
            };
      };
  faqs?:
    | T
    | {
        q?: T;
        a?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  name?: T;
  site?: T;
  status?: T;
  fields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  user?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-activities_select".
 */
export interface LeadActivitiesSelect<T extends boolean = true> {
  lead?: T;
  project?: T;
  type?: T;
  detail?: T;
  meta?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminder-rules_select".
 */
export interface ReminderRulesSelect<T extends boolean = true> {
  name?: T;
  project?: T;
  kind?: T;
  applyStatuses?: T;
  graceHours?: T;
  target?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminder-notices_select".
 */
export interface ReminderNoticesSelect<T extends boolean = true> {
  lead?: T;
  project?: T;
  rule?: T;
  kind?: T;
  receiver?: T;
  status?: T;
  dueAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}