/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    leads: Lead;
    projects: Project;
    sites: Site;
    categories: Category;
    media: Media;
    articles: Article;
    forms: Form;
    users: User;
    memberships: Membership;
    'lead-activities': LeadActivity;
    'reminder-rules': ReminderRule;
    'reminder-notices': ReminderNotice;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    leads: LeadsSelect<false> | LeadsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    'lead-activities': LeadActivitiesSelect<false> | LeadActivitiesSelect<true>;
    'reminder-rules': ReminderRulesSelect<false> | ReminderRulesSelect<true>;
    'reminder-notices': ReminderNoticesSelect<false> | ReminderNoticesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    username: string;
  };
  login: {
    password: string;
    username: string;
  };
  registerFirstUser: {
    password: string;
    username: string;
  };
  unlock: {
    username: string;
  };
}
/**
 * Customer leads from public forms and manual entry, tracked step by step.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  title?: string | null;
  /**
   * The project this lead belongs to.
   */
  project: number | Project;
  /**
   * Contact name.
   */
  name?: string | null;
  /**
   * Phone number (share with wechat at least one).
   */
  phone?: string | null;
  /**
   * WeChat ID (share with phone at least one).
   */
  wechat?: string | null;
  /**
   * Company or store name (optional).
   */
  company?: string | null;
  /**
   * Customer-stated need or current situation.
   */
  note?: string | null;
  /**
   * Lead source channel (for tagging).
   */
  source?: ('website' | 'campaign' | 'douyin' | 'xiaohongshu' | 'manual' | 'support' | 'referral') | null;
  /**
   * Current owner.
   */
  owner?: (number | null) | User;
  /**
   * Current follow-up stage.
   */
  status?: ('new' | 'contacted' | 'converted' | 'closed') | null;
  /**
   * Dedupe key (phone or wechat), auto-written.
   */
  dedupKey?: string | null;
  /**
   * Most recent follow-up note.
   */
  followUpNote?: string | null;
  /**
   * Reminder for the next follow-up.
   */
  nextFollowUpAt?: string | null;
  /**
   * Follow-up history timeline.
   */
  activity?:
    | {
        time: string;
        type?: ('call' | 'wechat' | 'visit' | 'quote') | null;
        summary?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Each product or focus area is a project; leads are grouped by project.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  /**
   * Unique URL-friendly English identifier.
   */
  slug: string;
  /**
   * One sentence on what this project does.
   */
  description?: string | null;
  /**
   * Current operating status.
   */
  status?: ('active' | 'beta' | 'archived') | null;
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  /**
   * Public homepage URL (optional).
   */
  url?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown as the lead owner, etc.
   */
  name?: string | null;
  /**
   * Determines accessible collections.
   */
  role?: ('operator' | 'editor' | 'admin') | null;
  /**
   * Profile image (optional).
   */
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  /**
   * For system notifications (optional).
   */
  email?: string | null;
  /**
   * Unique login username for the admin.
   */
  username: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manage covers, site logos, avatars and other image assets.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Accessibility alternative text; recommended for main images.
   */
  alt?: string | null;
  /**
   * Optional caption below the image.
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * A project can have multiple independent sites, each with its own SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  /**
   * The project this site belongs to.
   */
  project: number | Project;
  /**
   * Subdomain (e.g. demo), blank to use the project default.
   */
  subdomain?: string | null;
  /**
   * Path identifier (e.g. /home) to distinguish site pages.
   */
  pathSlug?: string | null;
  /**
   * Mark as a reusable template for cloning new sites.
   */
  isTemplate?: boolean | null;
  /**
   * Site publishing status.
   */
  status?: ('draft' | 'published' | 'archived') | null;
  /**
   * Site logo (400×100 transparent PNG recommended).
   */
  logo?: (number | null) | Media;
  /**
   * Accent color in hex, e.g. #2f8f96.
   */
  themeColor?: string | null;
  /**
   * Browser title, keep under 60 chars.
   */
  metaTitle?: string | null;
  /**
   * Search snippet, keep under 120 chars.
   */
  metaDescription?: string | null;
  /**
   * Social share preview image (1200×630).
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL identifier; blank will be derived from the name.
   */
  slug?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Product ideas, solutions and growth practices with rich text and images.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  /**
   * Cover image for cards and share previews.
   */
  coverImage?: (number | null) | Media;
  title: string;
  /**
   * Unique URL identifier; blank will be derived from the title.
   */
  slug: string;
  /**
   * The project this article belongs to.
   */
  project: number | Project;
  /**
   * One-line summary for list cards and excerpts.
   */
  excerpt?: string | null;
  /**
   * Article category (optional).
   */
  category?: (number | null) | Category;
  /**
   * Topic tags for grouping and search.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Byline; blank defaults to the organization name.
   */
  author?: string | null;
  /**
   * Estimated reading time; blank auto-estimates.
   */
  readingMinutes?: number | null;
  /**
   * Body content with headings, lists, quotes, code, images, etc.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Page title (≤60 chars); blank uses the article title.
   */
  seoTitle?: string | null;
  /**
   * Page summary (≤120 chars); blank uses the excerpt.
   */
  seoDescription?: string | null;
  /**
   * Drafts are admin-only; publish to go live.
   */
  status: 'draft' | 'published';
  /**
   * Publish time; auto-filled on publish if blank.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Define lead-capture form fields and submission target on public pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  name: string;
  /**
   * Owning site (optional, reusable globally).
   */
  site?: (number | null) | Site;
  /**
   * Only active forms are used on public pages.
   */
  status?: ('draft' | 'active') | null;
  /**
   * Field structure (JSON): names, required flags, order, etc.
   */
  fields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Multi-project governance: assign admin users to projects with scoped roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  title?: string | null;
  /**
   * The project this member belongs to.
   */
  project: number | Project;
  /**
   * The admin user account.
   */
  user: number | User;
  /**
   * owner/admin manage members; editor/owner/admin write; viewer read-only.
   */
  role: 'owner' | 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
}
/**
 * System-recorded key events for each lead. Read-only timeline of the lead lifecycle.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-activities".
 */
export interface LeadActivity {
  id: number;
  lead: number | Lead;
  project: number | Project;
  type: 'created' | 'status_changed' | 'assigned' | 'follow_up' | 'reminder';
  /**
   * Human-readable description of this event.
   */
  detail?: string | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Who triggered this event (auto-written).
   */
  actor?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Configure follow-up reminder rules (due / first-response SLA), consumed by the scheduled scan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminder-rules".
 */
export interface ReminderRule {
  id: number;
  name: string;
  /**
   * Empty means a global rule for all projects.
   */
  project?: (number | null) | Project;
  kind: 'due' | 'sla';
  applyStatuses: ('new' | 'contacted' | 'converted' | 'closed')[];
  /**
   * Only for SLA: exceeds this many hours since creation without first response.
   */
  graceHours?: number | null;
  /**
   * Empty means remind the lead owner.
   */
  target?: (number | null) | User;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Follow-up records triggered by reminder rules; mark as done when handled.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminder-notices".
 */
export interface ReminderNotice {
  id: number;
  lead: number | Lead;
  project: number | Project;
  rule: number | ReminderRule;
  kind: 'due' | 'sla';
  /**
   * Rule target or the lead owner.
   */
  receiver?: (number | null) | User;
  status: 'open' | 'done';
  /**
   * When the reminder was due.
   */
  dueAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null)
    | ({
        relationTo: 'lead-activities';
        value: number | LeadActivity;
      } | null)
    | ({
        relationTo: 'reminder-rules';
        value: number | ReminderRule;
      } | null)
    | ({
        relationTo: 'reminder-notices';
        value: number | ReminderNotice;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  name?: T;
  phone?: T;
  wechat?: T;
  company?: T;
  note?: T;
  source?: T;
  owner?: T;
  status?: T;
  dedupKey?: T;
  followUpNote?: T;
  nextFollowUpAt?: T;
  activity?:
    | T
    | {
        time?: T;
        type?: T;
        summary?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  status?: T;
  contactName?: T;
  contactEmail?: T;
  contactPhone?: T;
  url?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  project?: T;
  subdomain?: T;
  pathSlug?: T;
  isTemplate?: T;
  status?: T;
  logo?: T;
  themeColor?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  coverImage?: T;
  title?: T;
  slug?: T;
  project?: T;
  excerpt?: T;
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  author?: T;
  readingMinutes?: T;
  body?: T;
  seoTitle?: T;
  seoDescription?: T;
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  name?: T;
  site?: T;
  status?: T;
  fields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  username?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  title?: T;
  project?: T;
  user?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-activities_select".
 */
export interface LeadActivitiesSelect<T extends boolean = true> {
  lead?: T;
  project?: T;
  type?: T;
  detail?: T;
  meta?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminder-rules_select".
 */
export interface ReminderRulesSelect<T extends boolean = true> {
  name?: T;
  project?: T;
  kind?: T;
  applyStatuses?: T;
  graceHours?: T;
  target?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reminder-notices_select".
 */
export interface ReminderNoticesSelect<T extends boolean = true> {
  lead?: T;
  project?: T;
  rule?: T;
  kind?: T;
  receiver?: T;
  status?: T;
  dueAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}