links:
  - from: decision://astro-page-copy-cms/plan
    to: decision://phase1-skeleton
    created: '2026-09-20T10:30:17.116Z'
  - from: decision://astro-page-copy-cms/delivery
    to: decision://astro-page-copy-cms/plan
    created: '2026-09-21T00:15:21.095Z'
